# Generated by Django 4.0 on 2021-12-26 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('endpoints', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MLAlgorightm',
            new_name='MLAlgorithm',
        ),
    ]
